public  class collections {
    public void trialMap(){
        Map < String, string > mapNAme = new Map < string, string > () ;
        mapNAme.put('first key', 'sec value');
        mapNAme.put('sec color' , 'value orange');
        mapNAme.put('third fruit', 'value apple');
        system.debug('result: ' + mapNAme);
        system.debug('we will use get function: ' + mapNAme.get('third fruit'));
        system.debug('all the keyset are here: ' + mapNAme.keyset());
        system.debug('all the values: ' + mapNAme.values());

    }















    // public void listMethod(){
    //     List<Integer> firstListName = new List<Integer>();
    //     firstListName.add(5);
    //     firstListName.add(7);
    //     firstListName.add(34);
    //     Integer a =  firstListName.get(0);
    //     system.debug('our List: ' + firstListName);
    //     system.debug('get function: ' + a);

    //     set < string> secListName = new set<string>();
    //     secListName.add('Captain America');
    //     secListName.add('Hulk');
    //     secListName.add('spider Man');
    //     secListName.add('kiz');
    //     system.debug(secListName);
    //     system.debug('size: ' + secListName.size());
        
    
}
