public with sharing class newparameter {
    public string firstmethod (string firstName, string lastName){
        string fullName = firstName + lastName;
        return fullName;
    }
    public integer secMethod (integer a, integer b, integer c){
        integer sum = a + b + c;
        return sum;
    }
    public string thirdMethod (string anything){
        string secondd = anything.reverse();
        return secondd;
    }

}
