newparameter newobj = new newparameter();
string fullName = newobj.firstmethod('Hal', ' Myrat');
system.debug ('full name: ' + fullName);
integer sum = newobj.secMethod(4,6,8);
system.debug('sum of the numbers: ' + sum);
integer sum2 = newobj.secMethod(10,20,30);
system.debug ('second sum of the numbers: ' + sum2);
string secondd = newobj.thirdMethod ('Hello');
system.debug('reversed version: ' + secondd);
